# Generated by Django 5.2.7 on 2026-02-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('developer', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.DateField()),
            ],
        ),
    ]
