# Generated by Django 6.0.2 on 2026-02-22 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('developer', models.CharField(max_length=100, verbose_name='Разработчик')),
                ('producer', models.CharField(max_length=100, verbose_name='Издатель')),
                ('operating_system', models.CharField(max_length=100, verbose_name='Операционная система')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('year', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='FavouriteGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favourite_games', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favourite_games', to='rating_site.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Любимая игра',
                'verbose_name_plural': 'Любимые игры',
                'constraints': [models.UniqueConstraint(fields=('user', 'game'), name='unique_favourite_per_user_game')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='rating_site.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'constraints': [models.UniqueConstraint(fields=('game', 'user'), name='unique_review_per_user_game')],
            },
        ),
    ]
