# Generated by Django 6.0.2 on 2026-02-22 14:52

from pathlib import Path
import csv
from datetime import datetime, date

from django.conf import settings
from django.db import migrations


def parse_release_date(value: str) -> date:
    """
    Преобразует строку из CSV в date.
    Поддерживает:
    - '1985'
    - '1996'
    - 'June 24, 2015'
    - 'November 30, 1996'
    """
    if not value:
        return date(1900, 1, 1)

    value = value.strip()

    # Только год
    if value.isdigit() and len(value) == 4:
        return date(int(value), 1, 1)

    # Полная дата в формате "Month DD, YYYY"
    for fmt in ("%B %d, %Y", "%b %d, %Y"):
        try:
            return datetime.strptime(value, fmt).date()
        except ValueError:
            pass

    return date(1900, 1, 1)


def load_games(apps, schema_editor):
    Game = apps.get_model("rating_site", "Game")

    csv_path = Path(settings.BASE_DIR) / "data/computer_games.csv"

    games_to_create = []

    with open(csv_path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)

        for row in reader:
            name = (row.get("Name") or "").strip()
            developer = (row.get("Developer") or "").strip()
            producer = (row.get("Producer") or "").strip()
            genre = (row.get("Genre") or "").strip()
            operating_system = (row.get("Operating System") or "").strip()
            released_raw = (row.get("Date Released") or "").strip()

            if not name:
                continue

            games_to_create.append(
                Game(
                    name=name,
                    developer=developer[:100],
                    producer=producer[:100],
                    operating_system=operating_system[:100],
                    genre=genre[:100],
                    year=parse_release_date(released_raw),
                )
            )

    # ignore_conflicts=True не даст упасть, если запись с таким name уже есть
    Game.objects.bulk_create(games_to_create, ignore_conflicts=True, batch_size=500)


def unload_games(apps, schema_editor):
    Game = apps.get_model("rating_site", "Game")
    # Осторожный rollback: удаляем только записи, которые совпадают с CSV
    csv_path = Path(settings.BASE_DIR) / "computer_games.csv"

    if not csv_path.exists():
        return

    names = []
    with open(csv_path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = (row.get("Name") or "").strip()
            if name:
                names.append(name)

    if names:
        Game.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rating_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_games, reverse_code=unload_games),
    ]