# Generated by Django 6.0.2 on 2026-03-06 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_site', '0002_fill_games_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.jpg', upload_to='avatars/', verbose_name='Аватар')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('discord', models.CharField(blank=True, max_length=50, verbose_name='Discord')),
                ('games_rated', models.IntegerField(default=0, verbose_name='Оценено игр')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Написано отзывов')),
                ('favourite_count', models.IntegerField(default=0, verbose_name='В избранном')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
